<a href="https://colab.research.google.com/github/saraotaibii/PyTorch-/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
#Tensor Initializition
myTorch = torch.arange(10)
myTorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#reshape tensor
myTorch= myTorch.reshape(2,5)
#or
#myTorch= myTorch.view(2,5)

myTorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
#reshape if we dont know the number of the elements using -1
myTorch=myTorch.reshape(2,-1)
myTorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
# reshape and update
myTorch2 = torch.arange(10)
myTorch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
myTorch3 = myTorch2.reshape(2,-1)
myTorch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
#update myTorch2
myTorch2[1]= 444
myTorch2

tensor([  0, 444,   2,   3,   4,   5,   6,   7,   8,   9])

In [15]:
# myTorch3 is goining to be updated too
# so when you make a change to the orignal tensor with reshape and view that change will get reflected
myTorch3

tensor([[  0, 444,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [27]:
# slices
myTorch4 = torch.arange(10)
myTorch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
print(myTorch4[7]) # retreve the item in the 7th index
print(myTorch4[1:3]) # grab a slice


tensor(7)
tensor([1, 2])


In [38]:
myTorch4 = myTorch4.reshape(5,-1)
myTorch4


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [39]:
 #Grab a slice
myTorch4[:,1:] # all elements of the 1th col

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

### Tensor math operations

In [41]:
#  Create tensors
tensorA = torch.tensor([1,2,3,4])
tensorB = torch.tensor([3,2,9,2])

In [43]:
#Addtion
tensorA + tensorB
#or
torch.add(tensorA,tensorB)

tensor([ 4,  4, 12,  6])

In [45]:
#subtraction
tensorA - tensorB
#or
torch.sub(tensorA,tensorB)

tensor([-2,  0, -6,  2])

In [46]:
#Multiplcation
tensorA * tensorB
#or
torch.mul(tensorA,tensorB)

tensor([ 3,  4, 27,  8])

In [47]:
#Division
tensorA / tensorB
#or
torch.div(tensorA,tensorB)

tensor([0.3333, 1.0000, 0.3333, 2.0000])

In [48]:
#Mod
tensorA % tensorB
#or
torch.remainder(tensorA,tensorB)

tensor([1, 0, 3, 0])

In [49]:
#Exponents
tensorA ** tensorB
#or
torch.pow(tensorA,tensorB)

tensor([    1,     4, 19683,    16])

In [55]:
#reassignment
print(tensorA.add(tensorB))
print(tensorA)

tensor([ 4,  4, 12,  6])
tensor([1, 2, 3, 4])
